### ISSUE TITLE
Please enable github sponsors

### ISSUE THREAD

**Issue by bharatvaj** [LinArcX/wmenu#2]
Hey man thanks for this! Your tool saves me a lot of time to a point where I feel guilty to use it for free. Please enable github sponsors so I can pay you.

**Comment by LinArcX** [comment]
Hello and thank you so much for this energy.

I really appreciate your help and support.

Hope this software helps you and other people.

I enabled librepay method. If you need another method, let me know.

**Comment by bharatvaj** [comment]
Liberapay is perfect. Closing the issue now.
